#!/bin/bash
#
# start - this script starts and stops the application
#
# chkconfig:   - 85 15
#maintainer morro-wind mail address imorrowind#hotmail.com
#The script all application {start|stop|restart}

USER_HOME=/usr/mpsp

do_start()
{
    for i in `find $USER_HOME -path ${USER_HOME}/appBakeup -prune -o \
        -path ${USER_HOME}/shengchan_bak -prune -o \
        -path ${USER_HOME}/lazy -prune -o \
        -path ${USER_HOME}/yunxing -prune -o -name "serv.sh" -exec dirname {} \;`
    do
        sed -i '/^tail/s/^/#/' ${i}/serv.sh
    	/bin/bash ${i}/serv.sh 2>/dev/null
    done

    for i in `find ${USER_HOME} -path ${USER_HOME}/appBakeup -prune -o \
        -path ${USER_HOME}/shengchan_bak -prune -o \
        -path ${USER_HOME}/lazy -prune -o \
        -path ${USER_HOME}/yunxing -prune -o -name "run.sh" -exec dirname {} \;`
    do
        sed -i '/^tail/s/^/#/' ${i}/run.sh

        [ -f ${i}/runv.sh ] && '/^tail/s/^/#/' ${i}/runv.sh
        [ -f ${i}/runs ] && /bin/bash ${i}/runs
          sleep 3
        [ -f ${i}/stop.sh ] && /bin/bash ${i}/stop.sh
          sleep 3
        [ -f ${i}/run.sh ] && /bin/bash ${i}/run.sh 2>/tmp/bankper-err.log
    done

    for i in `find ${USER_HOME}/run/ -regex ".*d$" -exec basename {} \;`
    do
        cd ${USER_HOME}/run
        /bin/bash $i 2>/dev/null
    done
}

do_stop()
{
    for i in `find ${USER_HOME} -path ${USER_HOME}/appBakeup -prune -o \
        -path ${USER_HOME}/shengchan_bak -prune -o \
        -path ${USER_HOME}/lazy -prune -o \
        -path ${USER_HOME}/yunxing -prune -o -name "serv.sh" -exec dirname {} \;`
    do
        cd $i
        /bin/bash unserv.sh 2>/dev/null
    done

    for i in `find ${USER_HOME} -path ${USER_HOME}/appBakeup -prune -o \
        -path ${USER_HOME}/shengchan_bak -prune -o \
        -path ${USER_HOME}/lazy -prune -o \
        -path ${USER_HOME}/yunxing -prune -o -name "run.sh" -exec dirname {} \;`
    do
        cd $i
        /bin/bash runs 2>/dev/null
    done

    for i in `find ${USER_HOME}/run/ -regex ".*s$" -exec basename {} \;`
    do
        /bin/bash $i 2>/dev/null
    done
}

case "$1" in
    start)
        do_start
        ;;
    stop)
        do_stop
        ;;
    restart)
        do_stop
        do_start
        ;;
    *)
        echo "Usage: {start|stop|restart}" >&2
        exit 3
        ;;
esac
