---
# deployment app dest host
- name: push {{ app_name }} file
  copy:
    src: "{{ app_name }}.war"
    dest: "{{ app_path }}/webapps/"
    owner: tomcat
    group: tomcat
    mode: 0644

# delete dest host file
- name: delete {{ app_name }}
  file:
    path: "{{ app_path }}/webapps/{{ app_name }}"
    state: absent
