- name: Synchronization of src to dest on the remote hosts
  synchronize:
    src: "{{ SRC }}"
    dest: "{{ DEST }}"
    rsync_opts:
      - "--exclude=.git --exclude=.gitignore"
      - "--checksum"
      - "--delete"
        #      - "--owner=root --group=root"
