#!/bin/bash
#
#
#
#
#
#   APP_NAME
#   APP_HOME
#   JAVA_HOME
#   CLASSPATH

APP_NAME=javaapp
APP_PATH=/usr/mpsp
APP_BIN=
JAVA_PATH=/usr/java/default
JAVA_EXE=${JAVA_HOME}/bin/java
CONSOLE_OUT=
CLASS_HOME=

CLASSPATH=
JAVA_OPTS="-Xms512m -Xmx512m"

PIDFILE=/usr/mpsp/pid/${APP_NAME}.pid

test -x $JAVA_EXE || exit 0

[ -d $APPLIB_HOME ] || exit 0

#if [ -f $APPLIB_HOME ];then
#    for line in `find /usr/mpsp/plat2-paybusi/v2/app/lib/ -regex '.*jar$'`
#    do
#        CLASSPATH=$CLASSPATH:$line
#    done
#fi

if [ ! -z "$CLASSPATH" ] ; then
    CLASSPATH="$CLASSPATH":
fi


case "$1" in
    start)
        if [ -f $PIDFILE ];then
            echo "$PIDFILE exists, process is already running or crashed"
        else
            echo "Starting ${APP_NAME} service..."

            for line in `find $CLASS_HOME -regex '.*jar$'`
            do
                CLASSPATH="$CLASSPATH""$line"
            done

            nohup $JAVA_EXE $JAVA_OPTS \
                -Dflag=$APP_NAME \
                -classpath $CLASSPATH \
                -Djava.security.manager \
                -Djava.security.policy== $APP_POLICY \
                -Djava.rmi.server.codebase=file://${APP_BIN}/ \
                com.umpay.StartServer \
                >> "$CONSOLE_OUT" 2>&1 "&"
            echo $! > $PIDFILE
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ];then
            echo "$PIDFILE does not exist, process is not running"
        else
            PID=$(cat $PIDFILE)
            echo "Stopping..."
            kill -s QUIT $PID
            while [ -x /proc/${PID} ]
            do
                echo "Waiting for ${APP_NAME} to shutdown ..."
                sleep 1
            done
            retval=$?
            echo
            [ $retval -eq 0 ] && rm -f $lockfile
            echo "${APP_NAME} stopped"
        fi
        ;;
    status)
        PID=$(cat $PIDFILE)
        if [ ! -x /proc/${PID} ];then
            echo '${APP_HOME} is not running'
        else
            echo "${APP_HOME} is running ($PID)"
        fi
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Please use start, stop, restart or status as first argument"
        ;;
esac
