apiVersion: v1
kind: Service
metadata:
  labels:
    app: example
  name: example
#  namespace: default
spec:
  ports:
  - name: http
    port: 30101
    targetPort: http
  selector:
    app: example
  type: NodePort
